# Generated by Django 3.2.5 on 2022-04-15 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ad_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
